name: Application CI
on:
  push:
    branches:
    - 'main'
    - 'develop'
    - 'release/**'
    - 'releases/**'
    - 'hotfix/**'
    - 'feature/**'
    - 'feat/**'
    paths-ignore:
    - 'docs/**'
  workflow_dispatch:
jobs:
  build-and-push:
    uses: john-afrano/.github/.github/workflows/dispatcher.yaml@main
    with:
      runner_template: 'ubuntu-latest'
      github_sha: ${{ github.sha }}
      github_repository: ${{ github.repository }}
      github_run_number: ${{ github.run_number }}
      github_ref_name: ${{ github.ref_name }}
      docker_context: '.'
      docker_file_name: './Dockerfile'
      helm_directory: 'helm'
      helm_repository_url: ${{ vars.URL_HELM_REPOSITORY }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HELM_REPO_PAT: ${{ secrets.TOKEN_HELM_STORE }}
